SECRET_LEVEL_BUTTON = 'SCRT_LVL'

COMPLETE_TASK = 'CMPL_TASK'

ANIME = 'ANIME'
PLANNED = 'PLANNED'
VIEWED = 'VIEWED'

COMPLETE = 'Выполнена'
CANCELL = 'Отмена'

CONFIRM_DECLINE_BROADCAST = 'CNFM_DCLN_BRDCST'
CONFIRM_BROADCAST = 'CONFIRM'
DECLINE_BROADCAST = 'DECLINE'
